sudo: false 
language: python
cache: pip
python:
      - 3.5
install: pip install -r requirements/dev.txt
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database iws_test;' -U postgres
script: ./manage.py test
