version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  postgres:
    build: ./container/compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  flask:
    build:
      context: .
      dockerfile: ./container/compose/flask/Dockerfile
    user: flask
    depends_on:
      - postgres
    command: /gunicorn.sh
    env_file: .env

  nginx:
    build: ./container/compose/nginx
    depends_on:
      - flask

    ports:
      - "0.0.0.0:80:80"
