"""empty message

Revision ID: 32ac0747d4cb
Revises: aa2b820c37e3
Create Date: 2016-10-25 16:05:21.995861

"""

# revision identifiers, used by Alembic.
revision = '32ac0747d4cb'
down_revision = 'aa2b820c37e3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    ### end Alembic commands ###
