"""empty message

Revision ID: c05ed437b768
Revises: 006a83e83b1a
Create Date: 2016-10-14 09:56:26.984816

"""

# revision identifiers, used by Alembic.
revision = 'c05ed437b768'
down_revision = '006a83e83b1a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_client_id_fkey', 'requests', type_='foreignkey')
    op.create_foreign_key(None, 'requests', 'users', ['client_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.create_foreign_key('requests_client_id_fkey', 'requests', 'clients', ['client_id'], ['id'])
    ### end Alembic commands ###
